const actionStyles = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  UP_QUANTITY: "UP_QUANTITY",
  DOWN_QUANTITY: "DOWN_QUANTITY",
};

export default actionStyles;
